- name: restart strongswan
  service: name=strongswan state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart apparmor
  service: name=apparmor state=restarted

- name: rereadcrls
  shell: ipsec rereadcrls; ipsec purgecrls
